baseURL = "https://jsanjosep.com/"
languageCode = "en"
title = "Deployment Test Site"
disableKinds = ["taxonomy", "term"]

[params]
description = "Dummy test website for GitHub Actions deployment verification"
