baseURL = "https://jsanjosep.com/"
languageCode = "en-us"
title = "Juan"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Juan"
  description = "Personal blog"

[permalinks]
  blog = "/blog/:year/:month/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
