baseURL = "https://jsanjosep.com/"
languageCode = "en-us"
title = "Juan's Tech Site"
disableKinds = ["taxonomy", "term"]

[params]
description = "Technical blog and code uploads - Navy blue and white theme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  code = "/code/:slug/"
